# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, cypress ]
  pull_request:
    branches: [ main, cypress ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Build check ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'         
    - run: cd record-albums && npm ci
    - run: cd record-albums && npm run build --if-present

    - name: Unit Test check
    - run: cd record-albums && npm run test-headless    
    
    - name: Start server in the background
    - run: cd record-albums && npm start

    - name: Run e2e suite
    - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
